routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('index');
});
Route::resource('product', 'productController');
Route::resource('order', 'orderController');
Route::get('orders', 'productController@orders')->name('orders.list');

app/products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class products extends Model
{
    protected $table = 'products';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'stock',
        'price',
        'category_id',
        'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at'
    ];

    public function category()
    {
        return $this->belongsTo(categories::class, 'category_id');
    }

    public function scopeFilter($query, $request)
    {
        if ($request->has('q')) {
            $query->where('nama', 'like', '%'.$request->get('q').'%');
        }


        return $query;
    }
}

app/Http/Controllers/productController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\products;
use App\categories;
use Illuminate\Support\Str;
use App\Http\Requests\ProductRequest;
use App\orders;


class productController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = products::Filter($request)->with('category')->paginate(10);
        $view = [
            'title' => 'Products',
            'data'  => $data
        ];

        return view('products.index')->with($view);
    }

    public function orders(Request $request)
    {
        $categories = categories::with('products')->get();
        $orders     = orders::with('order_details')->paginate(10);
        $view = [
            'title' => 'Products',
            'data'  => $categories,
            'orders'    => $orders
        ];

        return view('orders.index')->with($view);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = categories::get();
        $view = [
            'categories' => $categories
        ];

        return view('products.create')->with($view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        DB::beginTransaction(); /* PART: Begin transaction */

        try {
            $file = $request->img;
            $slug = Str::slug($file->getClientOriginalName(), '_');
            $photo = time() . $slug . '.' . $file->getClientOriginalExtension();
            products::create([
                'name'          => $request->name,
                'stock'         => $request->stock,
                'price'         => $request->price,
                'category_id'   => $request->category,
                'description'   => $request->description,
                'image'         => $photo
            ]);

            $this->SavePhotoNR($file, $photo, public_path('storage/products/'));

            DB::commit();

            // PART: Flash
            $request->session()->flash('messages', 'Berhasil Membuat data product');
            $request->session()->flash('type', 'success');

            return redirect()->route('product.index');
        } catch (\Exception $e) {
            DB::rollback();

            return $e->getmEssage();
        }

        
    }

    private function SavePhotoNR($image, $photo, $path)
    {
        $file = $image;
        $file->move($path, $photo);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/products/create.blade.php
@extends('welcome')

@section('content')
  @if ($errors->any())
      @foreach ($errors->all() as $error)
          <div class="alert alert-danger">{{$error}}</div>
      @endforeach
  @endif
  <h2>Tambah Data Product</h2>
  <div class="mt-5"></div>
  
  <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" name="name" id="name" class="form-control" placeholder="Masukkan Nama" value="{{ old('name') }}" required>
    </div>

    <div class="form-group">
      <label for="stock">stock</label>
      <input type="number" name="stock" id="stock" class="form-control"  value="{{ old('stock') }}" placeholder="Masukkan stock" required>
    </div>

    <div class="form-group">
      <label for="price">Price</label>
      <input type="number" name="price" id="price" class="form-control" value="{{ old('price') }}" placeholder="Masukkan Price" required>
    </div>

    <div class="form-group">
      <label for="name">Category</label>
      <select class="select2 form-control" name="category" required>
        @foreach($categories as $category)
          <option value="{{ $category->id }}">{{ $category->name }}</option>
        @endforeach
      </select>
    </div>

    <div class="form-group">
      <label for="desc">Description</label>
      <textarea name="description" id="desc" placeholder="Masukkan Deskripsi" value="{{ old('description') }}" class="form-control"></textarea>
    </div>

    <div class="form-group">
      <label for="image">Image</label>
      <input type="file" name="img" id="image">
    </div>
  
    <div>
      <ul>
        <li>Ekstensi: jpeg, jpg, png</li>
      </ul>
    </div>

    <div class="form-group text-right">
      <button type="submit" class="btn btn-success">Simpan</button>
    </div>


  </form>
@endsection

resources/views/products/index.blade.php
@extends('welcome')

@section('content')
  <div class="form-group text-right">
    <a href="{{ route('product.create') }}"><button class="btn btn-primary">Tambah Data</button></a>
  </div>
  <div class="mt-5"></div>
  <table class="table table-bordered table-striped">
    <thead class="thead-light">
      <tr>
        <th scope="col" width="1%">No</th>
        <th scope="col">name</th>
        <th scope="col">description</th>
        <th scope="col">stock</th>
        <th scope="col">price</th>
        <th scope="col">category</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach($data as $item)
        <tr>
          <th scope="row">{{ $loop->iteration }}</th>
          <td>{{ $item->name }}</td>
          <td>{{ $item->description }}</td>
          <td>{{ $item->stock }}</td>
          <td>{{ $item->price }}</td>
          <td>{{ $item->category->name }}</td>
          <td>
						<!-- <a href="">
							<button>Edit</button>
						</a>

						<a href="">
							<button>Hapus</button>
						</a> -->
					</td>
        </tr>
      @endforeach

    </tbody>
  </table>
  <div class="mt-5"></div>
  {{ $data->appends(request()->all())->links() }}
@endsection